version: '3.4'


services:
   productapi:
     container_name: product
     image: ${DOCKER_REGISTRY-}product
     build:
       context: .
       dockerfile: ProductService/Dockerfile
     ports:
       - 5001:80
     environment:
       - VIRTUAL_HOST=dev.webchuyenghiep.com.vn
       - VIRTUAL_PORT=80
       - LETSENCRYPT_HOST=dev.webchuyenghiep.com.vn
       - LETSENCRYPT_EMAIL=buitrungtinh130296@gmail.com
     networks:
       - backend-demo
   
   userapi:
     container_name: user
     image: ${DOCKER_REGISTRY-}user
     build:
       context: .
       dockerfile: UserService/Dockerfile
     ports:
       - 5002:80
     networks:
       - backend-demo   

   #yarp:
   # container_name: yarp
   # image: ${DOCKER_REGISTRY-}yarp
   # build:
   #   context: .
   #   dockerfile: ApiGateway/Dockerfile
   # ports:
   #   - 5000:80
   # networks:
   #   - backend

#volumes:
#  pgvol:
#  #pgadmin:
#  upload_data:
networks:
  backend-demo:
    driver: bridge
    external: true